authelia: "false"
bridge: vmbr0
cloudflaretunnel: "true"
cluster-issuer: staging
cores_k3s: "8"
disaster_recovery: k10
disksize: 400G
domain: ""
email: ""
external_ip: 1.2.3.4
externaldns: "false"
ha: "false"
iface: enp3s0
ingress: cloudflaretunnel
jellyfin: "false"
jellyseerr: "false"
kasten-k10: "false"
kubernetes_version: v1.25.6+k3s1
local_path: ""
loki: "false"
macaddr: 6E:1F:26:B6:DF:20
memory_k3s: "28672"
new_repo: ""
nextcloud: "false"
nginxingress: "false"
nzbget: "false"
pci_device: "0000:02:00.0"
pci_passthrough: intel
platform: proxmox
prowlarr: "false"
proxmox_node_name: beelink-sei12
proxmox_vm_name: k3s-beelink-01
radarr: "false"
root_password: topsecure
rtorrentflood: "false"
shared-media-disk: 100Gi
smtp_domain: example.com
smtp_host: mail.example.com
smtp_port: "587"
smtp_sender: homelab@example.com
smtp_username: homelab@example.com
sonarr: "false"
ssh_password: demotime
ssh_private_key: ~/.ssh/id_rsa
ssh_public_key: ~/.ssh/id_rsa.pub
ssh_server_address: 172.16.137.36
ssh_server_gateway: 172.16.137.254
ssh_server_netmask: "24"
ssh_username: loeken
storage: local-path
vaultwarden: "false"
whoami: "true"
