apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media
  namespace: media  # Specify the namespace "media" for the PVC
spec:
  storageClassName: "{{ .Values.sharedmedia.storageClass }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.sharedmedia.size }}"
